[WIP] Search support
elifesciences/api-sdk-php pull request #41
Opened 2016-11-02 09:56 UTC by giorgiosironi

The Search client represents directly the results.

2016-11-02 16:29 UTC, giorgiosironi commented
Ready for review.

2016-11-02 16:34 UTC, giorgiosironi commented on src/Client/PodcastEpisodes.php
> +                        $episodes[] = $episode = $this->denormalizer->denormalize($episode, PodcastEpisode::class, null, ['snippet' => true]);
not sure how it was working before, but in a list PodcastEpisodes are snippets; and without it tests explode

2016-11-03 13:33 UTC, thewilkybarkid requested changes
Haven't tried it out yet, but looks good!

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Client/PodcastEpisodes.php
> +                        $episodes[] = $episode = $this->denormalizer->denormalize($episode, PodcastEpisode::class, null, ['snippet' => true]);
Can't see what's changed here? Only the (superfluous) new line removal?

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Model/SearchSubjects.php
> +class SearchSubjects implements Iterator
`final`

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Model/SearchTypes.php
> +class SearchTypes implements IteratorAggregate, Countable
`final`

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Model/SearchTypes.php
> +    public function __construct($typesToResults)
`array`?

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Serializer/SearchSubjectsNormalizer.php
> +class SearchSubjectsNormalizer implements NormalizerInterface, DenormalizerInterface, NormalizerAwareInterface, DenormalizerAwareInterface
`final`

2016-11-03 13:33 UTC, thewilkybarkid commented on test/ApiTestCase.php
> +    protected function createCollectionJson(string $id, bool $isSnippet = false, bool $complete = false) : array
Does this need to be changed to `protected`?

2016-11-03 13:33 UTC, thewilkybarkid commented on test/Model/SearchSubjectsTest.php
> +            $this->assertInternalType('integer', $counter);
Should test the values here, rather than relying on higher level tests?

2016-11-03 13:33 UTC, thewilkybarkid commented on test/ValidatingStorageAdapter.php
> +        return var_export(
Might be better to use `json_encode()` and `JSON_PRETTY_PRINT`?

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Model/SearchSubjects.php
> +    public function __construct(array $subjects, array $results)
Mark as `@internal`.

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Model/SearchTypes.php
> +    public function __construct($typesToResults)
Mark as `@internal`.

2016-11-03 13:33 UTC, thewilkybarkid commented on src/Model/SearchSubjects.php
> +class SearchSubjects implements Iterator
Make `Countable` so it matches `SearchTypes`.

2016-11-03 14:21 UTC, giorgiosironi commented on src/Client/PodcastEpisodes.php
> +                        $episodes[] = $episode = $this->denormalizer->denormalize($episode, PodcastEpisode::class, null, ['snippet' => true]);
ah I didn't see line 104, I'll revert it

2016-11-03 18:53 UTC, thewilkybarkid approved these changes

2016-11-03 18:53 UTC, merged